
class Locators():
    sign_up_menu_btn = '//li/a[@id="signin2"]'
    new_user_name_input = '//input[@id="sign-username"]'
    new_password_input = '//input[@id="sign-password"]'
    confirm_sign_up_btn = '//button[contains(text(), "Sign up")]'
    log_in_menu_btn = '//li/a[@id="login2"]'
    user_name_input = '//input[@id="loginusername"]'
    password_input = '//input[@id="loginpassword"]'
    log_in_btn = '//button[contains(text(), "Log in")]'
    welcome_menu = '//li/a[@id="nameofuser"]'
    log_out_btn = '//li/a[@id="logout2"]'
    laptops_category_btn = '//div/a[contains(text(), "Laptops")]'
    laptop_item = '//div/h4/a[contains(text(), "ReplaceMe")]'
    add_to_cart_btn = '//div/a[contains(text(), "Add to cart")]'
    cart_menu_btn = '//li/a[@id="cartur"]'
    table_cell = '//tbody/tr/td'
    item_cart_table_cell = '//tbody/tr/td[contains(text(), "ReplaceMe")]'
